name: Deploy Documentation

on:
  pull_request:
    branches:
      - develop
    types:
      - closed
      
jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'  # Use Python 3.10.12

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install  # Ensure all dependencies are installed

      - name: Install IRkernel
        run: |
          pip install jupyter
          R -e 'install.packages(c("renv", "IRkernel"))'
          R -e 'IRkernel::installspec(user = TRUE)'

      - name: Install R dependencies
        run: |
          R -e "renv::restore()"

      - uses: actions/checkout@v2
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 


      - uses: actions/cache@v2
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Make file and deploy documentation
        run: |
          make
          git fetch origin gh-pages --depth=1
          poetry run mike set-default develop
          poetry run mike deploy develop -p
